export { SuperflagProvider } from "./provider.js"
export { createHostedTelemetryTransport } from "./telemetry.js"
export type { HostedTelemetryTransportOptions } from "./telemetry.js"
export {
  createTypedHooks,
  useBooleanFlag,
  useBooleanFlagDetails,
  useFlag,
  useFlagDetails,
  useFlags,
  useNumberFlag,
  useNumberFlagDetails,
  useObjectFlag,
  useObjectFlagDetails,
  useStringFlag,
  useStringFlagDetails,
  useSuperflagClient,
} from "./hooks.js"

export type {
  AttributeValue,
  CachedConfig,
  EvaluationContext,
  EvaluationErrorCode,
  EvaluationReason,
  Flag,
  FlagConfig,
  FlagKey,
  FlagType,
  FlagValue,
  FlagValueFor,
  Flags,
  JsonValue,
  ObjectFlagValue,
  RefreshReason,
  Rollout,
  Segment,
  Serve,
  StorageAdapter,
  SuperflagDiagnostic,
  SuperflagEvaluationDetails,
  SuperflagEvaluationEvent,
  SuperflagExposureEvent,
  SuperflagProviderProps,
  SuperflagReadyInfo,
  SuperflagHostedTelemetryOptions,
  SuperflagSource,
  SuperflagState,
  SuperflagStatus,
  SuperflagTelemetryIdentityInput,
  SuperflagTelemetryOptions,
  SuperflagTelemetryQueueOptions,
  SuperflagTrackOptions,
  SuperflagTrackResult,
  TargetingRule,
  TypedFlagValues,
  TypedSuperflagClient,
  TypedSuperflagHooks,
  UseFlagsResult,
  Variation,
} from "./types.js"

export type {
  FeatureEvent,
  FeatureEventDimension,
  PseudonymousSubject,
  TelemetryDiagnostic,
  TelemetryFlushResult,
  TelemetryShutdownResult,
  TelemetryTransport,
} from "@superflag-sh/core"
